"""add dashboard share links

Revision ID: 72b05cd6c227
Revises: c91e8f142ad7
Create Date: 2026-08-27 11:40:14.988324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72b05cd6c227'
down_revision: Union[str, Sequence[str], None] = 'c91e8f142ad7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dashboard_share_links',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dashboard_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_accessed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dashboard_id'], ['dashboards.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dashboard_share_links_dashboard_id'), 'dashboard_share_links', ['dashboard_id'], unique=False)
    op.create_index(op.f('ix_dashboard_share_links_token_hash'), 'dashboard_share_links', ['token_hash'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dashboard_share_links_token_hash'), table_name='dashboard_share_links')
    op.drop_index(op.f('ix_dashboard_share_links_dashboard_id'), table_name='dashboard_share_links')
    op.drop_table('dashboard_share_links')
    # ### end Alembic commands ###
