"""Add authentication rate limits

Revision ID: e30ee757e099
Revises: 991793443e87
Create Date: 2026-09-15 08:52:52.443753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e30ee757e099'
down_revision: Union[str, Sequence[str], None] = '991793443e87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_rate_limits',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('window_started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_index(op.f('ix_auth_rate_limits_expires_at'), 'auth_rate_limits', ['expires_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_auth_rate_limits_expires_at'), table_name='auth_rate_limits')
    op.drop_table('auth_rate_limits')
    # ### end Alembic commands ###
