from __future__ import annotations

from typing import Annotated, Literal

from pydantic import BaseModel, ConfigDict, Field, model_validator


# ---------------------------------------------------------------------------
# Shared configuration
# ---------------------------------------------------------------------------

class StrictSchema(BaseModel):
    """
    Reject fields that are not explicitly defined in the schema.

    This helps prevent the AI or frontend from silently sending unsupported
    chart and analysis settings.
    """

    model_config = ConfigDict(extra="forbid")


# ---------------------------------------------------------------------------
# Conversation request schemas
# ---------------------------------------------------------------------------

class ConversationMessage(StrictSchema):
    role: Literal["user", "assistant"]
    content: str = Field(min_length=1, max_length=4_000)


class QuestionRequest(StrictSchema):
    question: str = Field(
        min_length=1,
        max_length=2_000,
        description="The user's latest question or clarification answer.",
    )

    conversation_id: str | None = Field(
        default=None,
        max_length=100,
        description="Identifier used to connect clarification turns.",
    )

    history: list[ConversationMessage] = Field(
        default_factory=list,
        max_length=10,
        description="Recent conversation messages needed to interpret the request.",
    )


# ---------------------------------------------------------------------------
# Clarification schemas
# ---------------------------------------------------------------------------

class ClarificationOption(StrictSchema):
    value: str = Field(
        min_length=1,
        max_length=200,
        description="Machine-readable value returned when this option is selected.",
    )

    label: str = Field(
        min_length=1,
        max_length=200,
        description="Text displayed to the user.",
    )


class ClarificationResponse(StrictSchema):
    status: Literal["needs_clarification"] = "needs_clarification"

    conversation_id: str = Field(min_length=1, max_length=100)

    message: str = Field(
        min_length=1,
        max_length=1_000,
        description="The clarification question displayed to the user.",
    )

    options: list[ClarificationOption] = Field(
        default_factory=list,
        max_length=10,
        description="Optional predefined answers. Free-text answers remain allowed.",
    )

    allow_free_text: bool = True


# ---------------------------------------------------------------------------
# Analysis-plan schemas
# ---------------------------------------------------------------------------

class FilterCondition(StrictSchema):
    column: str = Field(min_length=1, max_length=200)

    operator: Literal[
        "eq",
        "ne",
        "gt",
        "gte",
        "lt",
        "lte",
        "contains",
        "in",
        "between",
        "is_null",
        "is_not_null",
    ]

    # The executor will validate the value against the actual column type.
    value: str | int | float | bool | list[str | int | float] | None = None


class DimensionSpec(StrictSchema):
    column: str = Field(min_length=1, max_length=200)

    alias: str = Field(min_length=1, max_length=200)

    time_granularity: Literal[
        "day",
        "week",
        "month",
        "quarter",
        "year",
    ] | None = None


class MeasureSpec(StrictSchema):
    column: str = Field(min_length=1, max_length=200)

    aggregation: Literal[
        "sum",
        "mean",
        "median",
        "min",
        "max",
        "count",
        "nunique",
    ]

    alias: str = Field(min_length=1, max_length=200)


class SortSpec(StrictSchema):
    column: str = Field(min_length=1, max_length=200)
    direction: Literal["asc", "desc"] = "asc"


class AnalysisPlan(StrictSchema):
    """
    A declarative plan generated by the AI and executed by trusted Python code.

    It describes what pandas should calculate but contains no Python code.
    """

    intent: str = Field(
        min_length=1,
        max_length=1_000,
        description="Short explanation of what the analysis will calculate.",
    )

    dimensions: list[DimensionSpec] = Field(
        default_factory=list,
        max_length=3,
    )

    measures: list[MeasureSpec] = Field(
        default_factory=list,
        min_length=1,
        max_length=5,
    )

    filters: list[FilterCondition] = Field(
        default_factory=list,
        max_length=20,
    )

    sort: list[SortSpec] = Field(
        default_factory=list,
        max_length=5,
    )

    row_limit: int = Field(default=100, ge=1, le=1_000)

    chart_type: Literal[
        "line",
        "bar",
        "area",
        "pie",
    ]

    @model_validator(mode="after")
    def validate_chart_requirements(self) -> AnalysisPlan:


        if self.chart_type == "pie":
            if len(self.dimensions) != 1:
                raise ValueError(
                    "A pie chart requires exactly one dimension."
                )

            if len(self.measures) != 1:
                raise ValueError(
                    "A pie chart requires exactly one measure."
                )

        if self.chart_type in {"line", "bar", "area"}:
            if not self.dimensions:
                raise ValueError(
                    f"A {self.chart_type} chart requires at least one dimension."
                )

        return self


# ---------------------------------------------------------------------------
# Chart-response schemas
# ---------------------------------------------------------------------------

ChartValue = str | int | float | bool | None
ChartRow = dict[str, ChartValue]


class ChartAxis(StrictSchema):
    key: str = Field(
        min_length=1,
        max_length=200,
        description="Key in each chart data row.",
    )

    label: str = Field(min_length=1, max_length=200)

    value_type: Literal[
        "category",
        "number",
        "date",
        "datetime",
    ]


class ChartSeries(StrictSchema):
    key: str = Field(
        min_length=1,
        max_length=200,
        description="Key in each chart data row.",
    )

    label: str = Field(min_length=1, max_length=200)

    format: Literal[
        "number",
        "integer",
        "currency",
        "percent",
    ] = "number"

    currency: str | None = Field(
        default=None,
        min_length=3,
        max_length=3,
        description="ISO currency code such as USD or JOD.",
    )

    @model_validator(mode="after")
    def validate_currency(self) -> ChartSeries:
        if self.format == "currency" and self.currency is None:
            raise ValueError(
                "A currency series must include a currency code."
            )

        if self.format != "currency" and self.currency is not None:
            raise ValueError(
                "Currency can only be provided when format is 'currency'."
            )

        return self


class ChartSpec(StrictSchema):
    id: str = Field(min_length=1, max_length=100)

    type: Literal[
        "line",
        "bar",
        "area",
        "pie",
        "scatter",
    ]

    title: str = Field(min_length=1, max_length=300)

    subtitle: str | None = Field(default=None, max_length=500)

    x_axis: ChartAxis

    series: list[ChartSeries] = Field(
        min_length=1,
        max_length=10,
    )

    data: list[ChartRow] = Field(
        max_length=1_000,
        description="Calculated chart values produced by the backend.",
    )


class CompletedAnalysisResponse(StrictSchema):
    status: Literal["complete"] = "complete"

    conversation_id: str = Field(min_length=1, max_length=100)

    answer: str = Field(
        min_length=1,
        max_length=10_000,
        description="Natural-language explanation of the results.",
    )

    charts: list[ChartSpec] = Field(
        default_factory=list,
        max_length=5,
    )

    assumptions: list[str] = Field(
        default_factory=list,
        max_length=10,
        description="Important interpretations made without clarification.",
    )

    warnings: list[str] = Field(
        default_factory=list,
        max_length=10,
        description="Data-quality or analysis limitations.",
    )



AskDatasetResponse = Annotated[
    ClarificationResponse | CompletedAnalysisResponse,
    Field(discriminator="status"),
]


class AnalysisDecision(StrictSchema):
    status: Literal["needs_clarification", "ready"]

    question: str | None = Field(
        default=None,
        min_length=1,
        max_length=1_000,
        description=(
            "A focused question for the user when status is "
            "'needs_clarification'."
        ),
    )

    options: list[ClarificationOption] = Field(
        default_factory=list,
        max_length=10,
    )

    plan: AnalysisPlan | None = Field(
        default=None,
        description="The analysis plan when status is 'ready'.",
    )

    @model_validator(mode="after")
    def validate_decision(self) -> "AnalysisDecision":
        if self.status == "needs_clarification":
            if self.question is None:
                raise ValueError(
                    "A clarification decision requires a question."
                )

            if self.plan is not None:
                raise ValueError(
                    "A clarification decision cannot contain an analysis plan."
                )

        if self.status == "ready":
            if self.plan is None:
                raise ValueError(
                    "A ready decision requires an analysis plan."
                )

            if self.question is not None:
                raise ValueError(
                    "A ready decision cannot contain a clarification question."
                )

            if self.options:
                raise ValueError(
                    "A ready decision cannot contain clarification options."
                )

        return self